# Dockerfile.backend
FROM python:3.12.3

ENV PYTHONDOWNTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requements.txt /app/
RUN pip install --upgrade pip && pip install -r requerements.txt

COPY . /app/

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]